import Nav from "./components/nav";
import "./css/globals.scss";
import "./css/webfonts/britti-sans-variable.css";
import type { Metadata } from "next";
import MarqueeCpt from "./components/marquee";
import Cookies from "./components/cookies";
import Systems from "./components/systems";
import Cursor from "./components/cursor";
import Scrollbar from "./components/scrollbar";
import ThemeToggle from "./components/theme";
import SendMail from "./components/mail";

export const metadata: Metadata = {
  title: "Aarkyv Studios — Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Cursor/>
        <Nav />
        <ThemeToggle/>
        <MarqueeCpt/>
        <Systems/>
        <main>{children}</main>
        <Cookies/>
        <Scrollbar/>
      </body>
    </html>
  );
}
